language: php
php:
  - '7.2'
install:
  - cp ./setup/conf.php ./includes/conf.php
  - composer install
services:
  - postgresql
before_script:
  - psql -c 'CREATE DATABASE "mlpvc-rr";' -U postgres
  - psql -c "CREATE USER \"mlpvc-rr\" WITH LOGIN PASSWORD 'example-password'" -U postgres
  - psql "mlpvc-rr" < ./setup/mlpvc-rr.pg.sql
dist: trusty
addons:
  postgresql: "9.6"
